- title: Knowing God
  author: J. I. Packer
  category: Theology
- title: The Holiness of God
  author: R. C. Sproul
  category: Theology
- title: 1776
  author: David McCullough
  category: History
- title: Washington: A Life
  author: Ron Chernow
  category: History
- title: The Disappearing Spoon
  author: Sam Kean
  category: Science
- title: A Brief History of Time
  author: Stephen Hawking
  category: Science
- title: The Fellowship of the Ring
  author: J. R. R. Tolkien
  category: Fantasy
- title: The Lion, the Witch and the Wardrobe
  author: C. S. Lewis
  category: Fantasy
